/** @type {import('tailwindcss').Config} */
module.exports = {
	content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
	safelist: [
		'text-sm',
		'text-md',
		'text-lg',
		'text-xl',
		'text-xxxl',
		'leading-sm',
		'leading-md',
		'leading-lg',
		'leading-xl',
		'leading-xxxl',
		'font-normal',
		'font-semibold',
		'font-bold',
		'text-yellow',
		'text-red',
		'text-orange',
		'text-green',
		'text-blue',
		'text-gray',
		'text-neutral',
		'text-steel',
		'after:bg-yellow',
		'after:bg-red',
		'after:bg-orange',
		'after:bg-green',
		'after:bg-blue',
		'bg-yellow',
		'bg-red',
		'bg-orange',
		'bg-green',
		'bg-blue',
		'basis-10/12',
		'basis-1/12',
	],
	theme: {
		extend: {
			fontSize: {
				sm: '10px',
				md: '12px',
				lg: '14px',
				xl: '16px',
				xxxl: '20px',
			},
			lineHeight: {
				sm: '15px',
				md: '18px',
				lg: '21px',
				xl: '19.36px',
				xxxl: '30px',
			},
			fontFamily: {
				sans: ['Grtsk-Peta', 'sans-serif'],
			},
			textColor: {
				yellow: '#FDD206',
				red: '#FF5857',
				orange: '#FB7800',
				green: '#27AE60',
				blue: '#4792FF',
				gray: '#BCBCBC',
				neutral: '#DEDEDE',
				steel: '#909090',
				sky: '#6B7B94',
			},
			backgroundColor: {
				zinc: '#1C1C1C',
				black: '#000000',
				yellow: '#FDD206',
				red: '#FF5857',
				orange: '#FB7800',
				green: '#27AE60',
				blue: '#4792FF',
				'gray-light': '#343434',
			},
			fill: {
				blue: '#4792FF',
			},
			gridTemplateColumns: {
				'chart-1': 'minmax(100px, 1fr)',
				'chart-2': 'min-content minmax(100px, 1fr)',
				64: 'repeat(64, minmax(0, 1fr))',
			},
			gridColumn: {
				'span-32': 'span 32 / span 32',
				'span-44': 'span 44 / span 44',
				'span-20': 'span 20 / span 20',
			},
			gridTemplateRows: {
				'header-1': '26px',
			},
			gridAutoRows: {
				header: '32px 1fr',
			},
		},
	},
	plugins: [],
};
