{{- if (and .Values.cronjob (eq .Values.cronjob.enabled true)) }}
{{- $fullName := include "fullname" . -}}
---
{{- if .Capabilities.APIVersions.Has "batch/v1/CronJob" }}
apiVersion: batch/v1
{{- else }}
apiVersion: batch/v1beta1
{{- end }}
kind: CronJob
metadata:
  labels:
  {{- include "labels" $ | nindent 4 }}
  {{- if .Values.cronjob.additionalLabels }}
  {{- toYaml .Values.cronjob.additionalLabels | nindent 4 }}
  {{- end }}
  {{- if .Values.cronjob.annotations }}
  annotations:
  {{- toYaml .Values.cronjob.annotations | nindent 4 }}
  {{- end }}
  name: {{ $fullName }}-cronjob
spec:
  schedule: {{ .Values.cronjob.schedule | quote }}
  {{- if .Values.cronjob.successfulJobsHistoryLimit }}
  successfulJobsHistoryLimit: {{ .Values.cronjob.successfulJobsHistoryLimit }}
  {{- end }}
  {{- if .Values.cronjob.concurrencyPolicy }}
  concurrencyPolicy: {{ .Values.cronjob.concurrencyPolicy }}
  {{- end }}
  {{- if .Values.cronjob.failedJobsHistoryLimit }}
  failedJobsHistoryLimit: {{ .Values.cronjob.failedJobsHistoryLimit }}
  {{- end }}
  jobTemplate:
    spec:
      {{- if .Values.cronjob.parallelism }}
      parallelism: {{ .Values.cronjob.parallelism }}
      {{- end }}
      {{- if .Values.cronjob.completions }}
      completions: {{ .Values.cronjob.completions }}
      {{- end }}
      {{- if .Values.cronjob.activeDeadlineSeconds }}
      activeDeadlineSeconds: {{ .Values.cronjob.activeDeadlineSeconds }}
      {{- end }}
      {{- if .Values.cronjob.backoffLimit }}
      backoffLimit: {{ .Values.cronjob.backoffLimit }}
      {{- end }}
      {{- if .Values.cronjob.ttlSecondsAfterFinished }}
      ttlSecondsAfterFinished: {{ .Values.cronjob.ttlSecondsAfterFinished }}
      {{- end }}
      template:
        metadata:
          labels:
          {{- include "labels" $ | nindent 12 }}
          {{- with .Values.cronjob.additionalPodLabels }}
          {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.cronjob.additionalPodAnnotations }}
          annotations: 
          {{- toYaml . | nindent 12 }}
          {{- end }}
        spec:
          {{- if .Values.cronjob.restartPolicy }}
          restartPolicy: {{ .Values.cronjob.restartPolicy }}
          {{ else }}
          restartPolicy: OnFailure
          {{- end }}
          imagePullSecrets:
          - name: {{ .Values.global.imagePullSecrets | default "container-registry" }}
          containers:
          - name: {{ $fullName }}-cronjob
            {{- if .Values.cronjob.image }}
            image: "{{ .Values.cronjob.image.repository }}:{{ .Values.cronjob.image.tag }}"
            {{- else }}  
            image: "{{ .Values.global.image.repository }}:{{ .Values.global.image.tag }}"
            {{- end }}
            {{- if .Values.cronjob.imagePullPolicy }}
            imagePullPolicy: {{ .Values.cronjob.imagePullPolicy | default "Always" }}
            {{- else }}  
            imagePullPolicy: {{ .Values.global.imagePullPolicy | default "Always" }}
            {{- end }}
            {{- if .Values.cronjob.env }}
            env:
            {{- toYaml .Values.cronjob.env | nindent 14 }}
            {{- end }}
            envFrom:
            {{- if .Values.secrets.enabled }}
            - secretRef:
                name: {{ $fullName }}-secret
            {{- end }}
            {{- if .Values.cronjob.additionalEnvFrom  }}
            {{- range $value := .Values.cronjob.additionalEnvFrom.configMap }}
            - configMapRef:
                name: {{ $value }}
            {{- end }}
            {{- range $value := .Values.cronjob.additionalEnvFrom.secret }}
            - secretRef:
                name: {{ $value }}
            {{- end }}
            {{- end }}
            {{- if .Values.cronjob.command }}
            command: {{- include "tplvalues.render" (dict "value" .Values.cronjob.command "context" $) | nindent 12 }}
            {{- end }}
            {{- with .Values.cronjob.resources }}
            resources:
            {{- toYaml . | nindent 14 }}
            {{- end }}
            volumeMounts:   
            {{- range .Values.secrets.files }}
            - name: {{ $fullName }}-{{ .name | replace "." "-" }}
              mountPath: {{ .path }}
              subPath: {{ .name }}
            {{- end }}
            {{- range .Values.cronjob.additionalPVC }}
            - name: {{ .name }}
              mountPath: {{ .mountPath }}
            {{- end }}
            {{- if .Values.cronjob.additionalMounts }}
            {{- range .Values.cronjob.additionalMounts.secret }}
            - name: {{ .name }}
              mountPath: {{ .mountPath }}
              subPath: {{ (splitList "/" .mountPath ) | last }}
            {{- end }}
            {{- range .Values.cronjob.additionalMounts.configMap }}
            - name: {{ .name }}
              mountPath: {{ .mountPath }}
              subPath: {{ (splitList "/" .mountPath ) | last }}
            {{- end }}
            {{- end }}
            {{- if .Values.cronjob.containerSecurityContext }}
            securityContext:
            {{- toYaml .Values.cronjob.containerSecurityContext | nindent 14 }}
            {{- end }}
          {{- if .Values.cronjob.nodeSelector }}
          nodeSelector:
          {{- toYaml .Values.cronjob.nodeSelector | nindent 12 }}
          {{- end }}
          {{- if .Values.cronjob.tolerations }}
          tolerations:
          {{- toYaml .Values.cronjob.tolerations | nindent 12 }}
          {{- end }}
          {{- if .Values.cronjob.affinity }}
          affinity:
          {{- toYaml .Values.cronjob.affinity | nindent 12 }}
          {{- end }}
          {{- if .Values.cronjob.securityContext }}
          securityContext:      
          {{- toYaml .Values.cronjob.securityContext | nindent 12 }}
          {{- end }}        
          volumes:
          {{- range .Values.cronjob.additionalPVC }}
          - name: {{ .name }}
            persistentVolumeClaim:
              claimName: {{ .name }}
          {{- end }}
          {{- range .Values.secrets.files }}
          - name: {{ $fullName }}-{{ .name | replace "." "-" }}
            secret:
              secretName: {{ $fullName }}-{{ .name | replace "." "-" }}
          {{- end }}
          {{- if .Values.cronjob.additionalMounts }}
          {{- range .Values.cronjob.additionalMounts.secret }}
          - name: {{ .name }}
            secret:
              secretName: {{ .name }}
          {{- end }}
          {{- range .Values.cronjob.additionalMounts.configmap }}
          - name: {{ .name }}
            configMap:
              name: {{ .name }}
          {{- end }}
          {{- end }}
          {{- if (and .Values.rbac (eq .Values.rbac.enabled true) (eq .Values.rbac.serviceAccount.create true)) }}
          serviceAccountName: {{ .Values.rbac.serviceAccount.name }}
          {{- end }}
{{- end }}
