{{- if (and .Values.autoscaling (eq .Values.autoscaling.enabled true)) }}
{{- $fullName := include "fullname" . -}}
---
{{- if .Capabilities.APIVersions.Has "autoscaling/v2/HorizontalPodAutoscaler" }}
apiVersion: autoscaling/v2
{{- else }}
apiVersion: autoscaling/v2beta2
{{- end }}
kind: HorizontalPodAutoscaler
metadata:
  name: {{ $fullName }}
  labels:
  {{- include "labels" . | nindent 4 }}
  {{- with .Values.autoscaling.additionalLabels }}
  {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- if .Values.autoscaling.annotations }}
  annotations:
  {{- toYaml .Values.autoscaling.annotations | nindent 4 }}
  {{- end }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ $fullName }}
  minReplicas: {{ .Values.autoscaling.minReplicas }}
  maxReplicas: {{ .Values.autoscaling.maxReplicas }}
  metrics:
  {{- toYaml .Values.autoscaling.metrics | nindent 4 }}
{{- end }}