{{- if (and .Values.job (eq .Values.job.enabled true)) }}
{{- $fullName := include "fullname" . -}}
---
apiVersion: batch/v1
kind: Job
metadata:
  labels:
  {{- include "labels" $ | nindent 4 }}
  {{- if .Values.job.additionalLabels }}
  {{- toYaml .Values.job.additionalLabels | nindent 4 }}
  {{- end }}
  {{- if .Values.job.annotations }}
  annotations:
  {{- toYaml .Values.job.annotations | nindent 4 }}
  {{- end }}
  name: {{ $fullName }}-job
spec:
  {{- if .Values.job.parallelism }}
  parallelism: {{ .Values.job.parallelism }}
  {{- end }}
  {{- if .Values.job.completions }}
  completions: {{ .Values.job.completions }}
  {{- end }}
  {{- if .Values.job.activeDeadlineSeconds }}
  activeDeadlineSeconds: {{ .Values.job.activeDeadlineSeconds }}
  {{- end }}
  {{- if .Values.job.backoffLimit }}
  backoffLimit: {{ .Values.job.backoffLimit }}
  {{- end }}
  {{- if .Values.job.ttlSecondsAfterFinished }}
  ttlSecondsAfterFinished: {{ .Values.job.ttlSecondsAfterFinished }}
  {{- end }}
  template:
    metadata:
      labels:
      {{- include "labels" $ | nindent 8 }}
      {{- with .Values.job.additionalPodLabels }}
      {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.job.additionalPodAnnotations }}
      annotations: 
      {{- toYaml . | nindent 8 }}
      {{- end }}
    spec:
      restartPolicy: {{ .Values.job.restartPolicy | default "Never" }}
      containers:
      - name: {{ $fullName }}-job
        {{- if .Values.job.image }}
        image: "{{ .Values.job.image.repository }}:{{ .Values.job.image.tag }}"
        {{- else }}  
        image: "{{ .Values.global.image.repository }}:{{ .Values.global.image.tag }}"
        {{- end }}
        {{- if .Values.job.imagePullPolicy }}
        imagePullPolicy: {{ .Values.job.imagePullPolicy | default "Always" }}
        {{- else }}  
        imagePullPolicy: {{ .Values.global.imagePullPolicy | default "Always" }}
        {{- end }}
        {{- if .Values.job.env }}
        env:
        {{- toYaml .Values.job.env | nindent 10 }}
        {{- end }}
        envFrom:
        {{- if .Values.secrets.enabled }}
        - secretRef:
            name: {{ $fullName }}-secret
        {{- end }}
        {{- if .Values.job.additionalEnvFrom  }}
        {{- range $value := .Values.job.additionalEnvFrom.configMap }}
        - configMapRef:
            name: {{ $value }}
        {{- end }}
        {{- range $value := .Values.job.additionalEnvFrom.secret }}
        - secretRef:
            name: {{ $value }}
        {{- end }}
        {{- end }}
        {{- if .Values.job.command }}
        command: {{- include "tplvalues.render" (dict "value" .Values.job.command "context" $) | nindent 8 }}
        {{- end }}
        {{- with .Values.job.resources }}
        resources:
        {{- toYaml . | nindent 10 }}
        {{- end }}
        volumeMounts:   
        {{- range .Values.secrets.files }}
        - name: {{ $fullName }}-{{ .name | replace "." "-" }}
          mountPath: {{ .path }}
          subPath: {{ .name }}
        {{- end }}
        {{- range .Values.job.additionalPVC }}
        - name: {{ .name }}
          mountPath: {{ .mountPath }}
        {{- end }}
        {{- if .Values.job.additionalMounts }}
        {{- range .Values.job.additionalMounts.secret }}
        - name: {{ .name }}
          mountPath: {{ .mountPath }}
          subPath: {{ (splitList "/" .mountPath ) | last }}
        {{- end }}
        {{- range .Values.job.additionalMounts.configMap }}
        - name: {{ .name }}
          mountPath: {{ .mountPath }}
          subPath: {{ (splitList "/" .mountPath ) | last }}
        {{- end }}
        {{- end }}
        {{- if .Values.job.containerSecurityContext }}
        securityContext:
        {{- toYaml .Values.job.containerSecurityContext | nindent 10 }}
        {{- end }}      
      {{- if .Values.job.nodeSelector }}
      nodeSelector:
      {{- toYaml .Values.job.nodeSelector | nindent 8 }}
      {{- end }}
      {{- if .Values.job.tolerations }}
      tolerations:
      {{- toYaml .Values.job.tolerations | nindent 6 }}
      {{- end }}
      {{- if .Values.job.affinity }}
      affinity:
      {{- toYaml .Values.job.affinity | nindent 8 }}
      {{- end }}
      {{- if .Values.job.securityContext }}
      securityContext:      
      {{- toYaml .Values.job.securityContext | nindent 8 }}
      {{- end }}        
      volumes:
      {{- range .Values.job.additionalPVC }}
      - name: {{ .name }}
        persistentVolumeClaim:
          claimName: {{ .name }}
      {{- end }}
      {{- range .Values.secrets.files }}
      - name: {{ $fullName }}-{{ .name | replace "." "-" }}
        secret:
          secretName: {{ $fullName }}-{{ .name | replace "." "-" }}
      {{- end }}
      {{- if .Values.job.additionalMounts }}
      {{- range .Values.job.additionalMounts.secret }}
      - name: {{ .name }}
        secret:
          secretName: {{ .name }}
      {{- end }}
      {{- range .Values.job.additionalMounts.configmap }}
      - name: {{ .name }}
        configMap:
          name: {{ .name }}
      {{- end }}
      {{- end }}
      {{- if (and .Values.rbac (eq .Values.rbac.enabled true) (eq .Values.rbac.serviceAccount.create true)) }}
      serviceAccountName: {{ .Values.rbac.serviceAccount.name }}
      {{- end }}
{{- end }}