{{- if (and .Values.networkPolicy (eq .Values.networkPolicy.enabled true)) }}
{{- $fullName := include "fullname" . -}}
---
apiVersion: "networking.k8s.io/v1"
kind: NetworkPolicy
metadata:
  name: {{ $fullName }}
  labels:
  {{- include "labels" . | nindent 4 }}
  {{- if .Values.networkPolicy.additionalLabels }}
  {{- toYaml .Values.networkPolicy.additionalLabels | nindent 4 }}
  {{- end }}
  {{- if .Values.networkPolicy.annotations }}
  annotations:
  {{- toYaml .Values.networkPolicy.annotations | nindent 4 }}
  {{- end }}
spec:
  podSelector:
    matchLabels:
    {{- include "selectorLabels" . | nindent 6 }}
  {{- if .Values.deployment.podLabels }}
  {{- toYaml .Values.deployment.podLabels | nindent 6 }}
  {{- end }}
  {{- if or .Values.networkPolicy.ingress .Values.networkPolicy.egress }}
  policyTypes:
  {{- if .Values.networkPolicy.ingress }}
    - Ingress
  {{- end }}
  {{- if .Values.networkPolicy.egress }}
    - Egress
  {{- end }}
  {{- end }}
  {{- if .Values.networkPolicy.egress }}
  egress:
  {{- toYaml .Values.networkPolicy.egress | nindent 4 }}
  {{- end }}
  {{- if .Values.networkPolicy.ingress }}
  ingress:
  {{- toYaml .Values.networkPolicy.ingress | nindent 4 }}
  {{- end }}
  {{- end }}