{{- if (and .Values.prometheusRule (eq .Values.prometheusRule.enabled true)) }}
{{- $fullName := include "fullname" . -}}
---
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: {{ $fullName }}-prometheus-rule
  labels:
  {{- include "labels" . | nindent 4 }}
  {{- if .Values.prometheusRule.additionalLabels }}
  {{- toYaml .Values.prometheusRule.additionalLabels | nindent 4 }}
  {{- end }}
spec:
  groups:
  {{- toYaml .Values.prometheusRule.groups | nindent 4 }}
  {{- end -}}