{{- if (and .Values.rbac (eq .Values.rbac.enabled true) (eq .Values.rbac.serviceAccount.create true)) }}
{{- $fullName := include "fullname" . -}}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.rbac.serviceAccount.name | default $fullName }}
  labels:
  {{- include "labels" . | nindent 4 }}
  {{- with .Values.rbac.serviceAccount.additionalLabels }}
  {{- toYaml . | nindent 4 }}
  {{- end }}
  annotations:
  {{- with .Values.rbac.serviceAccount.annotations }}
  {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
