import { SINTERING_MACHINE_METRICS } from './consts';

export const sinteringMachineMetricsViews = [
	SINTERING_MACHINE_METRICS.tKol,
	SINTERING_MACHINE_METRICS.pKol,
	SINTERING_MACHINE_METRICS.tShihtPb,
	SINTERING_MACHINE_METRICS.tGorn,
	SINTERING_MACHINE_METRICS.speedAm,
	SINTERING_MACHINE_METRICS.speedLo,
	SINTERING_MACHINE_METRICS.tLo,
	SINTERING_MACHINE_METRICS.lev,
] as const;
